try:
    import requests
except:
    print("please wait installing 'requests' module... ")
    import subprocess

    subprocess.run("pip install requests")
    print("\n install finished. Re-start this tool.")

print('''
\t--------------------------------------------
\t \t \tWelcome to Admin Panel Finder
\t Design & developed by- 
\t \t \tDZ  Hacking Team
\t--------------------------------------------
''')

import requests

possibleAdminPage = [
    'admin/login',
    'admin1.php',
    'my-account',
    'admin1.html',
    'admin2.php',
    'admin2.html',
    'yonetim.php',
    'wp-admin',
    'wp-login',
    'yonetim.html',
    'yonetici.php',
    'yonetici.html',
    'ccms/',
    'ccms/login.php',
    'ccms/index.php',
    'maintenance/',
    'webmaster/',
    'adm/',
    'configuration/',
    'configure/',
    'websvn/',
    'admin/',
    'admin/account.php',
    'admin/account.html',
    'admin/index.php',
    'admin/index.html',
    'admin/login.php',
    'admin/login.html',
    'admin/home.php',
    'admin/controlpanel.html',
    'admin/controlpanel.php',
    'admin.php',
    'admin.html',
    'admin/cp.php',
    'admin/cp.html',
    'cp.php',
    'cp.html',
    'administrator/',
    'administrator/index.html',
    'administrator/index.php',
    'administrator/login.html',
    'administrator/login.php',
    'administrator/account.html',
    'administrator/account.php',
    'administrator.php',
    'administrator.html',
    'login.php',
    'login.html',
    'modelsearch/login.php',
    'moderator.php',
    'moderator.html',
    'moderator/login.php',
    'moderator/login.html',
    'moderator/admin.php',
    'moderator/admin.html',
    'moderator/',
    'account.php',
    'account.html',
    'controlpanel/',
    'controlpanel.php',
    'controlpanel.html',
    'admincontrol.php',
    'admincontrol.html',
    'adminpanel.php',
    'adminpanel.html',
    'admin1.asp',
    'admin2.asp',
    'yonetim.asp',
    'yonetici.asp',
    'admin/account.asp',
    'admin/index.asp',
    'admin/login',
    'admin/login.asp',
    'admin/home.asp',
    'admin/controlpanel.asp',
    'admin.asp',
    'admin/cp.asp',
    'cp.asp',
    'administrator/index.asp',
    'administrator/login.asp',
    'administrator/account.asp',
    'administrator.asp',
    'login.asp',
    'modelsearch/login.asp',
    'moderator.asp',
    'moderator/login.asp',
    'moderator/admin.asp',
    'account.asp',
    'controlpanel.asp',
    'admincontrol.asp',
    'adminpanel.asp',
    'fileadmin/',
    'fileadmin.php',
    'fileadmin.asp',
    'fileadmin.html',
    'administration/',
    'administration.php',
    'administration.html',
    'sysadmin.php',
    'sysadmin.html',
    'phpmyadmin/',
    'myadmin/',
    'sysadmin.asp',
    'sysadmin/',
    'ur-admin.asp',
    'ur-admin.php',
    'ur-admin.html',
    'ur-admin/',
    'Server.php',
    'Server.html',
    'Server.asp',
    'Server/',
    'administr8.php',
    'administr8.html',
    'administr8/',
    'administr8.asp',
    'webadmin/',
    'webadmin.php',
    'webadmin.asp',
    'webadmin.html',
    'administratie/',
    'admins/',
    'admins.php',
    'admins.asp',
    'admins.html',
    'administrivia/',
    'Database_Administration/',
    'WebAdmin/',
    'useradmin/',
    'sysadmins/',
    'admin1/',
    'system-administration/',
    'administrators/',
    'pgadmin/',
    'directadmin/',
    'staradmin/',
    'ServerAdministrator/',
    'SysAdmin/',
    'administer/',
    'LiveUser_Admin/',
    'sys-admin/',
    'typo3/',
    'panel/',
    'cpanel/',
    'cPanel/',
    'cpanel_file/',
    'platz_login/',
    'rcLogin/',
    'blogindex/',
    'formslogin/',
    'autologin/',
    'support_login/',
    'meta_login/',
    'manuallogin/',
    'simpleLogin/',
    'loginflat/',
    'utility_login/',
    'showlogin/',
    'memlogin/',
    'members/',
    'login-redirect/',
    'sub-login/',
    'ogin1/',
    'dir-login/',
    'login_db/',
    'xlogin/',
    'smblogin/',
    'customer_login/',
    'UserLogin/',
    'login-us/',
    'acct_login/',
    'admin_area/',
    'bigadmin/',
    'project-admins/',
    'phppgadmin/',
    'pureadmin/',
    'sql-admin/',
    'radmind/',
    'openvpnadmin/',
    'wizmysqladmin/',
    'vadmind/',
    'ezsqliteadmin/',
    'hpwebjetadmin/',
    'newsadmin/',
    'adminpro/',
    'Lotus_Domino_Admin/',
    'admin_index.asp',
    'admin_index.php',
    'user.php',
    'user.asp']

domain = "http://www." + input("Enter url (example.com): ")
status = requests.get(domain).status_code

try:
    try:
        for line in possibleAdminPage:
            finalLink = domain + "/" + line
            status = requests.get(finalLink).status_code

            if status == 404:
                print("Trying... " + line)
            elif status == 200:
                print("[FOUND] ", finalLink, status)
                # input("Press enter to continue or press CTRL+C to stop process. ")
    except:
        print("Process stopped. ")
        # input("")
except:
    print("Invalid url or check your internet connection.")
    input("Enter to exit ")
